# Generated by Django 3.2.8 on 2021-10-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('legajo', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('fecha_creación', models.DateTimeField(verbose_name='Fecha creación')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(verbose_name='Fecha inscripción')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.alumno')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.usuario'),
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.usuario')),
            ],
        ),
    ]
